---
name: 'Build'
on:
  pull_request: {}
  push: {}
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          submodules: true
      - uses: 'actions/cache@v3'
        with:
          path: 'packer_cache'
          key: 'packer_cache'

      - uses: 'hashicorp-contrib/setup-packer@v2'
      - run: 'packer init .'

      - run: 'make build'
      - uses: 'actions/upload-artifact@v3'
        with:
          name: 'image'
          path: 'build/*.img.gz'
          if-no-files-found: 'error'
